import { StyleSheet, Dimensions } from 'react-native';
import C from '../constants/colors';

const { width } = Dimensions.get('window');

export const s = StyleSheet.create({
  root:               { flex: 1, backgroundColor: C.offWhite },
  loaderScreen:       { flex: 1, backgroundColor: C.white, justifyContent: 'center', alignItems: 'center' },
  loaderLogo:         { width: 80, height: 80, borderRadius: 20, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: C.border },
  section:            { flex: 1, paddingHorizontal: 14, paddingTop: 14 },
  header:             { backgroundColor: C.headerBg, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 14, elevation: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4 },
  headerTitle:        { fontSize: 17, fontWeight: '900', color: C.white, letterSpacing: 0.2 },
  headerBtn:          { padding: 6, position: 'relative' },
  headerBadge:        { position: 'absolute', top: 2, right: 2, backgroundColor: C.error, borderRadius: 9, minWidth: 18, height: 18, justifyContent: 'center', alignItems: 'center', borderWidth: 1.5, borderColor: C.white },
  headerBadgeTxt:     { fontSize: 9, color: C.white, fontWeight: '900' },
  sectionLabel:       { fontSize: 12, fontWeight: '900', color: C.textLight, letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 10, marginTop: 6 },
  sidebar:            { position: 'absolute', left: 0, top: 0, bottom: 0, width: 280, backgroundColor: C.white, elevation: 20, shadowColor: '#000', shadowOffset: { width: 2, height: 0 }, shadowOpacity: 0.15, shadowRadius: 8, zIndex: 100 },
  sidebarOverlay:     { position: 'absolute', left: 0, top: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.45)', zIndex: 99 },
  sidebarHdr:         { backgroundColor: C.headerBg, padding: 20, paddingTop: 44, flexDirection: 'row', alignItems: 'center' },
  sidebarName:        { fontSize: 15, fontWeight: '900', color: C.white },
  sidebarCo:          { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  sidebarStatus:      { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 5 },
  sidebarDot:         { width: 7, height: 7, borderRadius: 4, backgroundColor: C.primary },
  sidebarStatusTxt:   { fontSize: 11, color: C.primaryLight, fontWeight: '700' },
  sidebarClose:       { padding: 6, marginLeft: 'auto' },
  menuItem:           { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12, position: 'relative' },
  menuItemOn:         { backgroundColor: C.primaryGhost },
  menuBar:            { position: 'absolute', left: 0, top: 8, bottom: 8, width: 3, backgroundColor: C.primary, borderRadius: 2 },
  menuIconWrap:       { width: 34, height: 34, borderRadius: 9, backgroundColor: C.offWhite, justifyContent: 'center', alignItems: 'center' },
  menuIconOn:         { backgroundColor: C.primary },
  menuTxt:            { flex: 1, fontSize: 14, fontWeight: '600', color: C.textMid },
  menuTxtOn:          { color: C.black, fontWeight: '800' },
  menuBadge:          { backgroundColor: C.error, borderRadius: 10, minWidth: 20, height: 20, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 4 },
  menuBadgeTxt:       { fontSize: 9, color: C.white, fontWeight: '900' },
  menuDivider:        { height: 1, backgroundColor: C.divider, marginHorizontal: 16, marginVertical: 8 },
  logoutItem:         { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 12 },
  welcomeCard:        { backgroundColor: C.primary, borderRadius: 16, marginBottom: 14, overflow: 'hidden', elevation: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  welcomeCardInner:   { flexDirection: 'row', alignItems: 'center', padding: 18, paddingBottom: 12 },
  welcomeGreet:       { fontSize: 13, color: C.primaryDark, fontWeight: '600' },
  welcomeName:        { fontSize: 22, fontWeight: '900', color: C.black, marginTop: 2 },
  welcomeTime:        { fontSize: 11, color: C.primaryDark, marginTop: 4 },
  welcomeStrip:       { flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.08)', paddingVertical: 12, paddingHorizontal: 16 },
  stripVal:           { fontSize: 22, fontWeight: '900', color: C.black, textAlign: 'center' },
  stripLbl:           { fontSize: 11, color: C.primaryDark, fontWeight: '700', marginTop: 2, textAlign: 'center' },
  stripDiv:           { width: 1, height: 32, backgroundColor: 'rgba(0,0,0,0.15)' },
  alertBanner:        { backgroundColor: C.warning, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, marginBottom: 10 },
  alertBannerTxt:     { flex: 1, color: C.white, fontWeight: '700', fontSize: 13 },
  pendingBanner:      { backgroundColor: C.primaryGhost, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, marginBottom: 8, borderWidth: 1, borderColor: C.border },
  pendingBannerTxt:   { flex: 1, color: C.textDark, fontWeight: '600', fontSize: 13 },
  pendingDot:         { width: 8, height: 8, borderRadius: 4 },
  statsGrid:          { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 14 },
  statCard:           { flex: 1, minWidth: (width - 48) / 2 - 5, backgroundColor: C.white, borderRadius: 12, padding: 14, alignItems: 'flex-start', borderWidth: 1, borderColor: C.divider, elevation: 1 },
  statIconWrap:       { width: 34, height: 34, borderRadius: 9, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  statValue:          { fontSize: 22, fontWeight: '900', color: C.textDark },
  statLabel:          { fontSize: 11, color: C.textLight, marginTop: 3, fontWeight: '600' },
  quickGrid:          { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 14 },
  quickBtn:           { flex: 1, minWidth: (width - 48) / 2 - 5, backgroundColor: C.white, borderRadius: 12, padding: 14, alignItems: 'center', borderWidth: 1, borderColor: C.divider, elevation: 1 },
  quickIconWrap:      { width: 48, height: 48, borderRadius: 14, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', marginBottom: 8 },
  quickLabel:         { fontSize: 12, fontWeight: '800', color: C.textDark, textAlign: 'center' },
  card:               { backgroundColor: C.white, borderRadius: 14, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: C.divider, elevation: 2, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, overflow: 'hidden', position: 'relative' },
  cardAccentBar:      { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4, borderTopLeftRadius: 14, borderBottomLeftRadius: 14 },
  cardTitle:          { fontSize: 15, fontWeight: '800', color: C.textDark, flex: 1 },
  chip:               { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, backgroundColor: C.primaryGhost, borderWidth: 1, borderColor: C.border, alignSelf: 'flex-start' },
  chipTxt:            { fontSize: 11, fontWeight: '700', color: C.primaryDark },
  prefChip:           { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9, paddingVertical: 4, borderRadius: 7, borderWidth: 1, alignSelf: 'flex-start', gap: 4 },
  prefChipTxt:        { fontSize: 11, fontWeight: '700' },
  prefBreakdown:      { backgroundColor: C.offWhite, borderRadius: 8, padding: 10, borderWidth: 1, borderColor: C.divider, marginBottom: 10 },
  prefBreakdownLabel: { fontSize: 10, fontWeight: '900', color: C.textLight, letterSpacing: 1 },
  detailRow:          { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailTxt:          { fontSize: 13, color: C.textMid, flex: 1, lineHeight: 18 },
  statsRow:           { flexDirection: 'row', backgroundColor: C.primaryGhost, borderRadius: 10, padding: 12, marginBottom: 12, alignItems: 'center' },
  statBox:            { flex: 1, alignItems: 'center', gap: 3 },
  statBoxVal:         { fontSize: 13, fontWeight: '800', color: C.textDark, textAlign: 'center' },
  statBoxLbl:         { fontSize: 10, color: C.textLight, fontWeight: '600', textAlign: 'center' },
  statDiv:            { width: 1, height: 32, backgroundColor: C.border },
  fuelBadge:          { flexDirection: 'row', alignItems: 'center', backgroundColor: C.primaryGhost, borderRadius: 10, padding: 10, marginBottom: 10, borderWidth: 1, borderColor: C.border },
  fuelIconBox:        { width: 36, height: 36, borderRadius: 9, backgroundColor: C.primaryPale, justifyContent: 'center', alignItems: 'center' },
  fuelBadgeType:      { fontSize: 12, fontWeight: '800', color: C.textDark },
  fuelBadgeVal:       { fontSize: 13, fontWeight: '700', color: C.primaryDark, marginTop: 2 },
  fuelBadgeNote:      { fontSize: 10, color: C.textLight, marginTop: 1 },
  srcBadge:           { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: C.offWhite, borderRadius: 7, padding: 7, borderWidth: 1, borderColor: C.divider },
  srcTxt:             { fontSize: 11, color: C.textMid, flex: 1 },
  stopsHeader:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderTopWidth: 1, borderTopColor: C.divider, marginTop: 8 },
  stopsTitle:         { fontSize: 13, fontWeight: '800', color: C.textDark },
  stopRow:            { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 7, borderBottomWidth: 1, borderBottomColor: C.divider },
  stopDot:            { width: 10, height: 10, borderRadius: 5, marginTop: 4, flexShrink: 0 },
  stopName:           { fontSize: 13, fontWeight: '700', color: C.textDark },
  stopAddr:           { fontSize: 11, color: C.textLight, marginTop: 2, lineHeight: 15 },
  paxRow:             { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: C.divider },
  paxAvatar:          { width: 32, height: 32, borderRadius: 16, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: C.border, flexShrink: 0 },
  scoreBubble:        { width: 48, height: 48, borderRadius: 24, borderWidth: 2.5, justifyContent: 'center', alignItems: 'center', backgroundColor: C.white, flexShrink: 0 },
  scoreNum:           { fontSize: 14, fontWeight: '900', lineHeight: 16 },
  scoreLbl:           { fontSize: 9, fontWeight: '700', color: C.textLight, marginTop: -1 },
  vIconWrap:          { width: 44, height: 44, borderRadius: 12, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: C.border, flexShrink: 0 },
  vBadge:             { flexDirection: 'row', alignItems: 'center', backgroundColor: C.primaryGhost, borderRadius: 10, padding: 12, borderWidth: 1, borderColor: C.border, marginBottom: 8 },
  vBadgeLbl:          { fontSize: 9, fontWeight: '900', color: C.textLight, letterSpacing: 1.2 },
  vBadgeVal:          { fontSize: 13, fontWeight: '700', color: C.textDark, marginTop: 2 },
  twoBtn:             { flexDirection: 'row', gap: 10, marginTop: 14 },
  btnTxt:             { fontSize: 14, fontWeight: '800', color: C.white },
  discardBtn:         { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, padding: 12, borderRadius: 10, backgroundColor: C.error },
  confirmBtnGreen:    { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, padding: 12, borderRadius: 10, backgroundColor: C.primary },
  rejectBtn:          { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, padding: 12, borderRadius: 10, backgroundColor: '#6B6B6B' },
  acceptBtn:          { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, padding: 12, borderRadius: 10, backgroundColor: C.primary },
  inputLabel:         { fontSize: 12, fontWeight: '800', color: C.textLight, letterSpacing: 0.8, marginBottom: 5, marginTop: 2, textTransform: 'uppercase' },
  input:              { backgroundColor: C.primaryGhost, borderRadius: 10, borderWidth: 1.5, borderColor: C.border, padding: 12, fontSize: 14, color: C.textDark, marginBottom: 10 },
  profileDivider:     { height: 1, backgroundColor: C.divider, marginVertical: 14 },
  profileIconWrap:    { width: 28, height: 28, borderRadius: 7, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', flexShrink: 0 },
  driverCard:         { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: C.white, borderRadius: 12, padding: 12, marginBottom: 8, borderWidth: 1, borderColor: C.divider, elevation: 1 },
  driverAvatar:       { width: 42, height: 42, borderRadius: 21, backgroundColor: C.primary, justifyContent: 'center', alignItems: 'center', position: 'relative', flexShrink: 0 },
  driverAvatarTxt:    { fontSize: 14, fontWeight: '900', color: C.black },
  driverDot:          { position: 'absolute', bottom: 1, right: 1, width: 11, height: 11, borderRadius: 6, borderWidth: 2, borderColor: C.white },
  driverName:         { fontSize: 14, fontWeight: '800', color: C.textDark },
  driverSub:          { fontSize: 11, color: C.textLight, marginTop: 2 },
  capRow:             { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 5 },
  capTxt:             { fontSize: 11, fontWeight: '700', color: C.textMid, minWidth: 28 },
  capBg:              { flex: 1, height: 5, backgroundColor: C.divider, borderRadius: 3, overflow: 'hidden' },
  capFill:            { height: 5, borderRadius: 3 },
  reqAvatar:          { width: 48, height: 48, borderRadius: 14, backgroundColor: C.primaryGhost, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: C.border },
  emptyState:         { alignItems: 'center', paddingVertical: 32 },
  emptyTxt:           { fontSize: 14, color: C.textLight, marginTop: 10, textAlign: 'center', fontWeight: '500', lineHeight: 20 },
  optimizingBanner:   { backgroundColor: C.primary, borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, marginBottom: 10 },
  optimizingTxt:      { flex: 1, fontWeight: '700', fontSize: 13 },
  trackingOverlay:    { position: 'absolute', bottom: 20, left: 16, right: 16, backgroundColor: 'rgba(0,0,0,0.7)', borderRadius: 10, flexDirection: 'row', alignItems: 'center', gap: 8, padding: 12 },
  trackingOverlayTxt: { color: C.white, fontWeight: '700', fontSize: 13, flex: 1 },
  viewMapBtn:         { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.primary, borderRadius: 10, padding: 12 },
  viewMapBtnTxt:      { flex: 1, fontSize: 13, fontWeight: '800', color: C.black },
  dateTabsContainer:  { flexDirection: 'row', backgroundColor: '#f0f0f0', borderRadius: 12, padding: 4, marginBottom: 14, gap: 4 },
  dateTab:            { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 10 },
  dateTabActive:      { backgroundColor: C.primary },
  dateTabText:        { fontSize: 12, color: C.textLight, fontWeight: '600' },
  dateTabTextActive:  { color: C.black, fontWeight: '800' },
  smartSuggestBox:    { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.primaryPale, borderRadius: 8, padding: 8, marginTop: 8, borderWidth: 1, borderColor: C.border },
  smartSuggestTxt:    { flex: 1, fontSize: 12, color: C.primaryDark, fontWeight: '600' },
  editDriverBtn:      { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.primary, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  editDriverBtnTxt:   { fontSize: 12, fontWeight: '800', color: C.black },
  warnBox:            { flexDirection: 'row', alignItems: 'flex-start', gap: 6, backgroundColor: C.warningLight, borderRadius: 7, padding: 8, marginBottom: 8, borderWidth: 1, borderColor: C.warning },
  warnTxt:            { fontSize: 11, color: C.warning, flex: 1, lineHeight: 15 },
});

export const clk = StyleSheet.create({
  overlay:       { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)', justifyContent: 'center', alignItems: 'center', padding: 16 },
  box:           { backgroundColor: C.white, borderRadius: 20, width: '100%', maxWidth: 340, overflow: 'hidden', elevation: 20 },
  hdr:           { backgroundColor: C.primary, flexDirection: 'row', alignItems: 'center', padding: 16 },
  hdrTxt:        { fontSize: 16, fontWeight: '900', color: C.black },
  digitalRow:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingTop: 20, paddingBottom: 10, paddingHorizontal: 20, gap: 4 },
  digitBox:      { backgroundColor: C.primaryGhost, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12, borderWidth: 2, borderColor: C.border },
  digitBoxOn:    { backgroundColor: C.primary, borderColor: C.primaryDark },
  digitTxt:      { fontSize: 36, fontWeight: '900', color: C.textDark },
  digitTxtOn:    { color: C.black },
  colon:         { fontSize: 36, fontWeight: '900', color: C.textDark, marginHorizontal: 2 },
  ampmCol:       { marginLeft: 10, gap: 5 },
  ampmBtn:       { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, backgroundColor: C.primaryGhost, borderWidth: 2, borderColor: C.border },
  ampmBtnOn:     { backgroundColor: C.primary, borderColor: C.primaryDark },
  ampmTxt:       { fontSize: 12, fontWeight: '800', color: C.textDark },
  ampmTxtOn:     { color: C.black },
  modeLabel:     { textAlign: 'center', fontSize: 10, fontWeight: '800', color: C.textLight, letterSpacing: 2, marginBottom: 8 },
  clockWrap:     { alignItems: 'center', paddingBottom: 10 },
  clockFace:     { backgroundColor: C.primaryGhost, borderWidth: 2, borderColor: C.border, position: 'relative' },
  clockNum:      { position: 'absolute', width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  clockNumTxt:   { fontWeight: '800' },
  centerDot:     { position: 'absolute', width: 10, height: 10, borderRadius: 5, backgroundColor: C.primaryDark },
  handLine:      { position: 'absolute', height: 3, backgroundColor: C.primaryDark, borderRadius: 2 },
  handDot:       { position: 'absolute', width: 20, height: 20, borderRadius: 10, backgroundColor: C.primary, borderWidth: 3, borderColor: C.primaryDark },
  quickMin:      { flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginBottom: 12, justifyContent: 'center' },
  quickMinBtn:   { flex: 1, paddingVertical: 8, borderRadius: 8, backgroundColor: C.primaryGhost, alignItems: 'center', borderWidth: 2, borderColor: C.border },
  quickMinBtnOn: { backgroundColor: C.primary, borderColor: C.primaryDark },
  quickMinTxt:   { fontSize: 13, fontWeight: '700', color: C.textDark },
  quickMinTxtOn: { color: C.black, fontWeight: '900' },
  actions:       { flexDirection: 'row', gap: 10, padding: 16, paddingTop: 4 },
  cancelBtn:     { flex: 1, padding: 14, borderRadius: 10, borderWidth: 2, borderColor: C.border, alignItems: 'center' },
  cancelTxt:     { fontWeight: '700', color: C.textDark, fontSize: 14 },
  confirmBtn:    { flex: 2, padding: 14, borderRadius: 10, backgroundColor: C.primary, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 },
  confirmTxt:    { color: C.black, fontWeight: '900', fontSize: 14 },
});